# =============================
# LPCPlus Configuration Example
# =============================
#
# This is a fully working example configuration for LPCPlus.
# It supports LuckPerms prefixes, suffixes, colors, and PlaceholderAPI.
# Reload config with /lpcplus reload
#
# Placeholders:
# {message} - the chat message
# {name} - the player's username
# {displayname} - the player's nickname
# {world} - current world of the player
# {prefix} - player's highest priority prefix
# {suffix} - player's highest priority suffix
# {prefixes} - all prefixes (sorted by priority)
# {suffixes} - all suffixes (sorted by priority)
# {username-color} - username color from LuckPerms meta
# {message-color} - message color from LuckPerms meta

# Default chat format for players without a group-specific format
chat-format: "{prefix}{username-color}{name}&r: {message-color}{message}"

# Group-specific formats
group-formats:
  # Default group
  default: "{prefix}&f{name}&r: {message}" # &f = white, resets after prefix
  # VIP group with fancy hex colors
  #vip: "&#FFD700{prefix}&#FFD700{name}&r: &#FFFAAA{message}" # Gold-ish username and pale yellow message
  # Moderator/Staff group
  #mod: "&#00FFAA{prefix}&#00FFAA{name}&r: &#00FFDD{message}" # Cyan-green username, bright cyan message
  # Admin group
  #admin: "&#FF5555{prefix}&#FF5555{name}&r: &#FFAAAA{message}" # Bright red username, lighter red message

# =============================
# Notes
# =============================
# - Hex codes must be prefixed with '&#' and 6-digit hex (e.g., &#FF0000)
# - You can mix & codes and hex codes
# - Use {prefix} and {suffix} only if you set them in LuckPerms
# - {username-color} and {message-color} are optional meta keys from LuckPerms
# - You can create new groups by adding entries under group-formats
# - PlaceholderAPI placeholders can be included, e.g., {player_health}, {vault_eco_balance}
